name: deploy blog to cloud
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - name: checkout main
        uses: actions/checkout@master

      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # 安装 node:10
      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装 hexo
      - name: npm install
        run: |
          npm install -g hexo-cli
          npm install
        env:
          CI: true

      # 生成静态文件
      - name: hexo build
        run: |
          hexo clean
          hexo generate
        env:
          CI: true

      # 部署
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
