name: deploy blog to aliyun oss
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - name: checkout main
        uses: actions/checkout@master

      # 安装 node:10
      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # 安装 hexo
      - name: npm install
        run: |
          npm install -f -g hexo-cli
          npm install -f
        env:
          CI: true
      
      # 生成静态文件
      - name: hexo build
        run: |
          hexo generate
        env:
          CI: true

      # 安装 ossutil
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-guangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      
      # 部署
      - name: depoly
        run: |
          ossutil cp -rf public oss://hexo-blog-yleoer/
        env:
          CI: true